{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "testchartname.serviceAccountName" . }}
  labels:
{{ include "testchartname.labels" . | indent 4 }}
{{- end -}}
