apiVersion: v1
kind: Pod
metadata:
  labels:
   run: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.redis_image.repository }}:{{ .Values.redis_image.tag }}
    name: redis
    ports:
    - name: 
      containerPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}


